{% set version = "1.0.0" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: patsy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/patsy/patsy-{{ version }}.tar.gz
  sha256: 787d2a5d15333fb1e4dc11331b2e7fd17d92f9a815db2fbca29b50c0e6c0159d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.4.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
    - scipy
  imports:
    - patsy
  commands:
    - pip check
    - pytest -vv --color=yes --pyargs patsy --cov=patsy --cov-branch --cov-report=term-missing:skip-covered --cov-fail-under=47

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas
  doc_url: https://patsy.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
