{% set version = "0.5.4" %}

package:
  name: patsy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/patsy/patsy-{{ version }}.tar.gz
  sha256: 7dabc527597308de0e8f188faa20af7e06a89bdaa306756dfc7783693ea16af4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.4.0
    - python >=3.6
    - six
    - scipy

test:
  imports:
    - patsy

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
