{% set version = "0.5.6" %}

package:
  name: patsy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/patsy/patsy-{{ version }}.tar.gz
  sha256: 95c6d47a7222535f84bff7f63d7303f2e297747a598db89cf5c67f0c0c7d2cdb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.4.0
    - python >=3.6
    - six

test:
  imports:
    - patsy
  commands:
    - pip check
    - pytest -vv --color=yes --pyargs patsy --cov=patsy --cov-branch --cov-report=term-missing:skip-covered --cov-fail-under=47
  requires:
    - pip
    - pytest-cov
    - scipy

about:
  home: https://github.com/pydata/patsy
  license: BSD-2-Clause AND PSF-2.0
  license_family: BSD
  license_file: LICENSE.txt
  summary: Describing statistical models in Python using symbolic formulas
  doc_url: https://patsy.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - croth1
